# Generated by Django 5.1.6 on 2025-03-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='unknown author', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='https://images.pexels.com/photos/185764/pexels-photo-185764.jpeg?auto=compress&cs=tinysrgb&w=600', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='decription of the book', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(),
        ),
    ]
