# Generated by Django 5.1.7 on 2025-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_order_book_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
