# Generated by Django 5.1.7 on 2025-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
    ]
